<?php

class Apedic_Training_Model_Entity_Attribute_Backend_Customer_Customerhobbies extends Mage_Eav_Model_Entity_Attribute_Backend_Abstract{
    public function afterLoad($object)
    {
        return parent::afterLoad($object); // TODO: Change the autogenerated stub
    }

    public function beforeSave($object)
    {
        return parent::beforeSave($object); // TODO: Change the autogenerated stub
    }
}